### ISSUE TITLE
Not clearing memory

### ISSUE THREAD

**Issue by philosodad** [bitpay/bitpay-c-keyutils#8]
There seems to be a memory leak or other problem in the SIN generation code that is preventing the use of SSL downstream from the function being called.

This must be resolved to resolve dependent bug in perl key utilities.

https://github.com/bitpay/bitpay-perl-keyutils/issues/3

**Comment by philosodad** [comment]
Closed with release https://github.com/bitpay/bitpay-c-keyutils/releases/tag/v2.0.3

**Comment by denji** [comment]
```
[key_utils.c:192] -> [key_utils.c:198]: (performance) Variable 'res' is reassigned a value before the old one has been used.
[key_utils.c:352]: (error) Memory leak: byteData
```
